# Generated by Django 4.0 on 2022-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aideitem',
            name='titre',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
