# Generated by Django 4.0.3 on 2022-03-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0003_alter_aideitem_titre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aideitem',
            options={'verbose_name': "Texte d'aide", 'verbose_name_plural': "Textes d'aide"},
        ),
    ]
