# Generated by Django 4.0.3 on 2022-04-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pim', '0004_alter_aideitem_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aideitem',
        ),
    ]
