# Generated by Django 4.0.3 on 2023-02-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diname', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attractivite',
            options={'ordering': ('code',)},
        ),
        migrations.AddField(
            model_name='attractivite',
            name='libelle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
