# Generated by Django 4.0.3 on 2023-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diname', '0002_alter_attractivite_options_attractivite_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractivite',
            name='couleur',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
