# Generated by Django 4.0.10 on 2024-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diname', '0005_rename_libelle_attractivite_lbl_mges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emplois',
            options={'ordering': ('etablissement', 'libelle_emploi')},
        ),
        migrations.AlterModelOptions(
            name='famille',
            options={'ordering': ('surface',)},
        ),
        migrations.AlterField(
            model_name='emplois',
            name='etablissement',
            field=models.CharField(choices=[('EXPLOITATION', 'EXPLOITATION'), ('FC', 'FC'), ('MAINTENANCE', 'MAINTENANCE'), ('DI', 'DI')], max_length=50),
        ),
    ]
