# Generated by Django 4.0.3 on 2022-03-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ursaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('taux_cs', models.DecimalField(decimal_places=2, max_digits=4)),
                ('taux_cs_non_soumise', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.DeleteModel(
            name='ursaff',
        ),
    ]
