# Generated by Django 4.0.3 on 2022-03-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0002_ursaffmodel_delete_ursaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('localisation', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=20)),
                ('Repas', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Nuit_Pdj', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
