# Generated by Django 4.0.3 on 2022-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0003_bareme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bareme',
            name='Nuit_Pdj',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bareme',
            name='Repas',
            field=models.FloatField(),
        ),
    ]
