# Generated by Django 4.0.3 on 2022-03-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0005_alter_ursaffmodel_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ursaffmodel',
            name='annee',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
