# Generated by Django 4.0.3 on 2022-03-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0006_alter_ursaffmodel_annee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ursaffmodel',
            options={'ordering': ('annee',)},
        ),
    ]
