# Generated by Django 4.0.3 on 2022-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0007_alter_ursaffmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bareme',
            options={'ordering': ('annee',)},
        ),
    ]
