# Generated by Django 4.0.3 on 2022-03-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0008_alter_bareme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ursaffmodel',
            name='annee',
            field=models.IntegerField(unique=True),
        ),
    ]
