# Generated by Django 4.0.3 on 2022-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0009_alter_ursaffmodel_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBareme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('annee', models.IntegerField()),
                ('file', models.FileField(upload_to='static/datas')),
            ],
        ),
    ]
