# Generated by Django 4.0.3 on 2022-04-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0010_newbareme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewBareme',
        ),
    ]
