# Generated by Django 4.0.10 on 2024-11-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frais', '0011_delete_newbareme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ursaffmodel',
            options={'ordering': ('-annee',)},
        ),
    ]
