# Generated by Django 4.0.10 on 2024-11-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coeff_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NR', models.IntegerField()),
                ('valeur', models.FloatField()),
                ('date_application', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date_application', 'NR'),
            },
        ),
        migrations.CreateModel(
            name='Echelon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echelon', models.IntegerField()),
                ('coeff', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('valeur', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snb_ref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('snb', models.FloatField()),
            ],
            options={
                'ordering': ('-annee',),
            },
        ),
        migrations.CreateModel(
            name='Snb_ref_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('snb', models.FloatField()),
                ('date_application', models.DateField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('-annee', '-date_application'),
            },
        ),
        migrations.CreateModel(
            name='TempsDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(max_length=10)),
                ('coeff', models.FloatField()),
            ],
        ),
    ]
