# Generated by Django 4.0.3 on 2022-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrilleSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('maj_res', models.FloatField()),
                ('coeff', models.FloatField()),
                ('Ech1', models.FloatField()),
                ('Ech2', models.FloatField()),
                ('Ech3', models.FloatField()),
                ('Ech4', models.FloatField()),
                ('Ech5', models.FloatField()),
                ('Ech6', models.FloatField()),
                ('Ech7', models.FloatField()),
                ('Ech8', models.FloatField()),
                ('Ech9', models.FloatField()),
                ('Ech10', models.FloatField()),
                ('Ech11', models.FloatField()),
                ('Ech12', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Snb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('snb', models.FloatField()),
            ],
        ),
    ]
