# Generated by Django 4.0 on 2022-05-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snb_ref',
            name='annee',
            field=models.IntegerField(unique=True),
        ),
    ]
