# Generated by Django 4.0.3 on 2022-04-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snb',
            new_name='Snb_ref',
        ),
    ]
