# Generated by Django 4.0.3 on 2022-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0002_rename_snb_snb_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='grillesalaire',
            name='NR',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
