# Generated by Django 4.0.3 on 2022-04-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0004_alter_grillesalaire_coeff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech10',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech11',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech12',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech5',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech6',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech7',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech8',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='grillesalaire',
            name='Ech9',
            field=models.FloatField(null=True),
        ),
    ]
