# Generated by Django 4.0.3 on 2022-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0006_alter_grillesalaire_nr_alter_grillesalaire_annee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coeff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NR', models.IntegerField()),
                ('valeur', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TempsDeTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree', models.CharField(max_length=10)),
                ('coeff', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='GrilleSalaire',
        ),
    ]
