# Generated by Django 4.0.3 on 2022-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0008_inflation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Echelon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echelon', models.IntegerField()),
                ('coeff', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Inflation',
        ),
    ]
