# Generated by Django 4.0.3 on 2022-04-14 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0009_echelon_delete_inflation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snb.snb_ref')),
            ],
        ),
    ]
