# Generated by Django 4.0.3 on 2022-04-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0010_inflation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snb_ref',
            options={'ordering': ('-annee',)},
        ),
        migrations.AlterField(
            model_name='snb_ref',
            name='annee',
            field=models.IntegerField(unique=True),
        ),
    ]
