# Generated by Django 4.0.3 on 2022-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0011_alter_snb_ref_options_alter_snb_ref_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snb_ref',
            name='annee',
            field=models.IntegerField(),
        ),
    ]
