# Generated by Django 4.0.3 on 2022-04-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0012_alter_snb_ref_annee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflation',
            name='annee',
            field=models.IntegerField(unique=True),
        ),
    ]
