# Generated by Django 4.0.10 on 2024-11-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snb', '0013_alter_inflation_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coeff_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NR', models.IntegerField()),
                ('valeur', models.FloatField()),
                ('date_application', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date_application', 'NR'),
            },
        ),
        migrations.CreateModel(
            name='Snb_ref_New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('snb', models.FloatField()),
                ('date_application', models.DateField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ('-annee', '-date_application'),
            },
        ),
        migrations.DeleteModel(
            name='Coeff',
        ),
        migrations.AlterField(
            model_name='snb_ref',
            name='annee',
            field=models.IntegerField(unique=True),
        ),
    ]
